name: feature-branch
on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
jobs:
  test:
    strategy:
      matrix:
        runtimes: [17, 21]
        runners: [ubuntu-latest]
    name: Unit Test
    runs-on: ${{matrix.runners}}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: 'true'
      - name: Setup JDK ${{matrix.runtimes}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.runtimes}}
          distribution: 'liberica'
      - name: Gradle Package
        run: ./gradlew clean bootJar
      - name: Gradle Verify
        run: ./gradlew clean check
